# Generated by Django 3.2.12 on 2022-07-02 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_user',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='Sub/', verbose_name='Profil resmi'),
        ),
    ]
