# Generated by Django 3.2.12 on 2022-07-02 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_izlenenler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='izlenenler',
            name='izlenen',
            field=models.ManyToManyField(null=True, related_name='izlenen', to='movies.Movie'),
        ),
    ]
