# Generated by Django 3.2.12 on 2022-07-02 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20220702_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='ekleyen',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
